sudo: required

language: generic

git:
  depth: false

dist:
  xenial

services:
  - docker

before_install:
  - docker pull moussavdb/build-nodejs

script:
  - docker run -v $PWD:/src -w /src moussavdb/build-nodejs yarn install
  - docker run -v $PWD:/src -w /src moussavdb/build-nodejs ng build --prod
