sudo: required

language: generic

git:
  depth: false

dist:
  xenial

cache:
  directories:
    - $HOME/.npm
    - $PWD/node_modules

services:
  - docker

before_install:
  - docker pull moussavdb/build-nodejs

script:
  - docker run -v $PWD:/src -v $HOME/.npm:/root/.npm -v $PWD/node_modules:/src/node_modules -w /src moussavdb/build-nodejs yarn install
  - docker run -v $PWD:/src -v $HOME/.npm:/root/.npm -v $PWD/node_modules:/src/node_modules -w /src moussavdb/build-nodejs ng build --prod
