image: moussavdb/yildiz-build-image

pipelines:
  default:
    - step:
        script:
          - mvn -V -B -s settings.xml package
  branches:
    master:
      - step:
          script:
            - mvn -V -B -s settings.xml org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR
    develop:
      - step:
          script:
            - openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in private-key.gpg.enc -out private-key.gpg -d
            - gpg --import --batch private-key.gpg
            - mvn -V -B -s settings.xml deploy
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/webapp.jar"
            - curl -H "Content-Type:application/json" --data '{"source_type":"Branch", "source_name":"develop"}' -X POST https://registry.hub.docker.com/u/moussavdb/webapp/trigger/${DOCKERHUB_TOKEN}/